### ISSUE TITLE
[main.py --training] error

### ISSUE THREAD

**Issue by natalymr** [bdqnghi/tbcnn-attention#2]
Hello, @bdqnghi!

When I tried to run the next command:
```
python3 main.py --model_path "model/104_pku_reduce_max_new" \
                --n_classes 104 --training
``` 
I got such error:
```
Traceback (most recent call last):
  File "main.py", line 249, in <module>
    main(opt)
  File "main.py", line 239, in main
    train_model(train_trees, val_trees,  labels, embeddings, embed_lookup , opt) 
  File "main.py", line 78, in train_model
    opt.aggregation
TypeError: init_net() missing 4 required positional arguments: 'weights', 'biases', 'aggregation_type', and 'distributed_function'
```

And, indeed, in `main.py` on the 77th line there is 
```
nodes_node, children_node, hidden_node, attention_score_node = network.init_net(
        num_feats,
        len(labels),
        opt.aggregation
    )
```

But in `network.py` the method `init_net` is defined as
```
def init_net(feature_size, label_size, output_size, weights, biases, aggregation_type, distributed_function)
```

**Comment by natalymr** [comment]
I think the solution is that in `main.py` the import
```
import network as network
```
should be replaced with this import
```
import network_2 as network
```

Am I right?
